<!DOCTYPE html>
<html>
    <head>
        <meta charset='UTF-8' />
        <title>STI</title>
        <?php
        // echo $this->headLink()->prependStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl() . '/css/style.css');
        ?>

        <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js'></script>

        <?php
        //echo $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl() . '/js/example.js');
        ?>
        <style type="text/css" >
            .err{
                color:#FF0000;
            }
            body
            {
                background-color:#FFFFCC;
            }

            .left_panel{
                border-top-width: 0;
                margin-left: 38px;
                margin-top: 59px;
            }

            .right_panel{
                border-left-width: 4px;
                margin-left: 489px;
                margin-top: -23px;
                background-color:#CC9933;
                width:35%;
            }
            .active{
                background: url(../images/active.png) no-repeat scroll center 39px transparent;
                font-weight: 700;
            }
            
            
        </style>
        <!--[if IE ]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script type="text/javascript">

            $(document).ready(function() {
                $('#password_err').text("");
                $('#new_password_err').text("");
                $('#re_password_err').text("");
                
                $('#change_password_form').submit(function() {
                    var counter=false;
                    if($('#password').val()=='')
                        $('#password_err').text("Please enter valid old password!");
                    else
                        $('#password_err').text("");

                    if($('#new_password').val()=='')
                        $('#new_password_err').text("Please enter valid new password!");
                    else
                        $('#new_password_err').text("");

                    if($('#re_password').val()=='')
                        $('#re_password_err').text("Please re-enter valid new password!");
                    else
                        $('#re_password_err').text("");

                    if(($('#password').val()!='')&&($('#new_password').val()!='')&&($('#re_password').val()!='')){
                        return true;
                    }
                    return false;

                });

            });

        </script>
    </head>
    <body>
        <h3 style="margin-left:90%;"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'logout'), null, true); ?>">Logout</a></h3>
        <div id="profile">
            <div class="left_panel">
                <table>
                    <tr><td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'userprofile'), null, true); ?>">Summary</a></td></tr>
                    <tr><td><h3>Make Profile changes:</h3> </td></tr>
                    <tr><td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'editprofile'), null, true); ?>">Change My Name and Email</a></td></tr>
                    <tr><td><a class="active" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'changepassword'), null, true); ?>">Change my password</a></td></tr>
                    <tr><td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'changeaddress'), null, true); ?>">Change my address</a></td></tr>
                </table>
            </div>
            <div class="right_panel">
                <form id="change_password_form" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'changepassword'), null, true); ?>" method="post" >
                    <table>
                        <tr>
                            <td><span class="err">*</span>old Password: </td>
                            <td><input type="password" id="password" name="password" value="" /><br/><span class="err" id="password_err"></span></td>
                        </tr>
                        <tr>
                            <td><span class="err">*</span>New Password: </td>
                            <td><input type="password" id="new_password" name="new_password" value="" /><br/><span class="err" id="new_password_err"></span></td>
                        </tr>
                        <tr>
                            <td><span class="err">*</span>Re-Password : </td>
                            <td><input type="password" id="re_password" name="re_password" value="" /><br/><span class="err" id="re_password_err"></span></td>
                        </tr>

                        <tr>
                            <td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'userprofile'), NULL, true); ?>">Cancel</a></td>
                            <td><input type="submit" value="Save Password"></td>
                        </tr>
                    </table>
                    <input type="hidden" id="id" name="id" value="<?php echo $this->id; ?>" />
                </form>
            </div>


        </div>



    <footer></footer>
</body>
</html>

