<!DOCTYPE html>
<html>
    <head>
        <meta charset='UTF-8' />
        <title>STI</title>
        <?php
        // echo $this->headLink()->prependStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl() . '/css/style.css');
        ?>

        <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js'></script>

        <?php
        //echo $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl() . '/js/example.js');
        ?>
        <style type="text/css" >
            .err{
                color:#FF0000;
            }
            body
            {
                background-color:#FFFFCC;
            }

            .left_panel{
                border-top-width: 0;
                margin-left: 38px;
                margin-top: 59px;
            }

            .right_panel{
                border-left-width: 4px;
                margin-left: 489px;
                margin-top: -23px;
                background-color:#CC9933;
                width:30%;
            }

            .active{
                background: url(../images/active.png) no-repeat scroll center 39px transparent;
                font-weight: 700;
            }

        </style>
        <!--[if IE ]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script type="text/javascript">

            $(document).ready(function() {
                $('#first_name_err').text("");
                $('#last_name_err').text("");
                $('#email_err').text("");
                $('#confirm_email_err').text("");
                




                $('#edit_form').submit(function() {
                    var counter=false;
                    if($('#first_name').val()==''){
                        $('#first_name_err').text("Please enter valid first name!");
                        counter=true;
                    }else
                        $('#first_name_err').text("");

                    if($('#last_name').val()==''){
                        $('#last_name_err').text("Please enter valid last name!");
                        counter=true;
                    }else
                        $('#last_name_err').text("");

                    if(($('#email').val()=='')&&($('#email').match(/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/))){
                        $('#email_err').text("Please enter valid email!");
                        counter=true;
                    } else
                        $('#email_err').text("");

                    if(($('#confirm_email').val()=='')&&($('#confirm_email').match(/^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/))&&($('#email').val()!=$('#confirm_email').val())){
                        $('#confirm_email_err').text("Email address doesn't match!");
                        counter=true;
                    }else
                        $('#confirm_email_err').text("");

                    if(($('#first_name').val()!='0')&&($('#last_name').val()!='')&&($('#email').val()!='')&&($('#confirm_email').val()!='')&&(counter)){
                        return true;
                    }
                    return false;

                });

            });

        </script>
    </head>
    <body>
        <h3 style="margin-left:90%;"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'logout'), null, true); ?>">Logout</a></h3>
        <div id="profile">
            <div class="left_panel">
                <table>
                    <tr><td><a class="active" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'userprofile'), null, true); ?>">Summary</a></td></tr>
                    <tr><td><h3>Make Profile changes:</h3> </td></tr>
                    <tr><td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'editprofile'), null, true); ?>">Change My Name and Email</a></td></tr>
                    <tr><td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'changepassword'), null, true); ?>">Change my password</a></td></tr>
                    <tr><td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'changeaddress'), null, true); ?>">Change my address</a></td></tr>
                </table>
            </div>
            <div class="right_panel">
                <form id="edit_form" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'editprofile'), null, true); ?>" method="post" >
                    <table>
                        <tr>
                            <td><span class="err">*</span>First Name: </td>
                            <td><input type="text" id="first_name" name="first_name" value="<?php echo $this->userInfo['first_name']; ?>" /><br/><span class="err" id="first_name_err"></span></td>
                        </tr>
                        <tr>
                            <td><span class="err">*</span>Last Name: </td>
                            <td><input type="text" id="last_name" name="last_name" value="<?php echo $this->userInfo['last_name']; ?>" /><br/><span class="err" id="last_name_err"></span></td>
                        </tr>
                        <tr>
                            <td><span class="err">*</span>Email: </td>
                            <td><input type="text" id="email" name="email" value="<?php echo $this->userInfo['email']; ?>" /><br/><span class="err" id="email_err"></span></td>
                        </tr>
                        <tr>
                            <td><span class="err">*</span>Confirm Email: </td><td><input type="text" id="confirm_email" name="confirm_email" value="" /><br/><span class="err" id="confirm_email_err"></span></td>
                        </tr>
                        <tr>
                            <td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'userprofile'), NULL, true); ?>">Cancel</a></td>
                            <td><input type="submit" value="Save"></td>
                        </tr>
                    </table>
                    <input type="hidden" id="id" name="id" value="<?php echo $this->userInfo->id; ?>" />
                </form>
            </div>


        </div>



    <footer></footer>
</body>
</html>

