<!DOCTYPE html>
<html>
    <head>
        <meta charset='UTF-8' />
        <title>STI</title>
        <?php
        // echo $this->headLink()->prependStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl() . '/css/style.css');
        ?>

        <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js'></script>

        <?php
        //echo $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl() . '/js/example.js');
        ?>
        <style type="text/css" >
            .err{
                color:#FF0000;
            }
            body
            {
                background-color:#FFFFCC;
            }

            #form{
                border-top-width: 1px;
                margin-left: 252px;
                margin-top: 68px;
                padding-left: 9px;
                padding-top: 8px;
                background-color:#CC9933;
                padding-right: 117px;
                width: 400px;
            }
        </style>
        <!--[if IE ]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script type="text/javascript">

            $(document).ready(function() {

                $('#email_err').text("");
               

                $('#forgot_form').submit(function() {
                    var counter=false;

                    if($('#email').val()=='')
                        $('#email_err').text("Please enter valid email!");
                    else
                        $('#email_err').text("");

                    if(($('#email').val()!='')){
                        return true;
                    }
                    return false;

                });


            });

        </script>
    </head>
    <body>
        <div id="form">
            <h3 style="margin-left: 121px;">Forgot Password</h3>
            <form id="forgot_form" action="<?php echo $this->url(array('controller' => 'index', 'action' => 'login'), null, true); ?>" method="post" >
                <table>
                    <tr>
                        <td>Email: </td>
                        <td><input type="text" id="email" name="email" /><br/><span class="err" id="email_err"></span></td>
                    </tr>
                    <tr>
                        <td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'forgotpassword'), NULL, true); ?>">Sign-up</a></td>
                        <td><input type="submit" value="submit"></td>
                    </tr>
                </table>
            </form>

        </div>


    <footer></footer>
</body>
</html>

