<!DOCTYPE html>
<html>
    <head>
        <meta charset='UTF-8' />
        <title>STI</title>
        <?php
        // echo $this->headLink()->prependStylesheet(Zend_Controller_Front::getInstance()->getBaseUrl() . '/css/style.css');
        ?>

        <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js'></script>

        <?php
        //echo $this->headScript()->appendFile(Zend_Controller_Front::getInstance()->getBaseUrl() . '/js/example.js');
        ?>
        <style type="text/css" >
            .err{
                color:#FF0000;
            }
            body
            {
                background-color:#FFFFCC;
            }

            .left_panel{
                border-top-width: 0;
                margin-left: 38px;
                margin-top: 59px;
            }

            .right_panel{
                border-left-width: 4px;
                margin-left: 489px;
                margin-top: -23px;
                background-color:#CC9933;
                width:30%;
            }

            .active{
                background: url(../images/active.png) no-repeat scroll center 39px transparent;
                font-weight: 700;
            }

        </style>
        <!--[if IE ]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <script type="text/javascript">

            $(document).ready(function() {

                $('#email_err').text("");
                $('#password_err').text("");




                $('#login_form').submit(function() {
                    var counter=false;

                    if($('#email').val()=='')
                        $('#email_err').text("Please enter valid email!");
                    else
                        $('#email_err').text("");

                    if($('#password').val()=='')
                        $('#password_err').text("Please enter valid password!");
                    else
                        $('#password_err').text("");

                    if(($('#email').val()!='')&&($('#password').val()!='')){
                        return true;
                    }
                    return false;

                });

            });

        </script>
    </head>
    <body>
        <h3 style="margin-left:90%;"><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'logout'), null, true); ?>">Logout</a></h3>
        <div id="profile">
            <div class="left_panel">
                <table>
                    <tr><td><a class="active" href="<?php echo $this->url(array('controller' => 'index', 'action' => 'userprofile'), null, true); ?>">Summary</a></td></tr>
                    <tr><td><h3>Make Profile changes:</h3> </td></tr>
                    <tr><td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'editprofile'), null, true); ?>">Change My Name and Email</a></td></tr>
                    <tr><td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'changepassword'), null, true); ?>">Change my password</a></td></tr>
                    <tr><td><a href="<?php echo $this->url(array('controller' => 'index', 'action' => 'changeaddress'), null, true); ?>">Change my address</a></td></tr>
                </table>
            </div>
            <div class="right_panel">
                <table> <tr><td>Name: </td><td><?php echo $this->userInfo['first_name'] . ' ' . $this->userInfo['last_name']; ?></td></tr>
                    <tr><td>Email: </td><td><?php echo $this->userInfo['email']; ?></td></tr>
                    <tr><td>Telephone No.</td> <td><?php echo $this->userInfo['telephone']; ?></td></tr>
                </table>
            </div>


        </div>


    <footer></footer>
</body>
</html>

